import type { TournamentDefinition } from "../workspace/schema";

export const TOURNAMENT_BASE: TournamentDefinition = {
  teams: [
    { code: "MEX", name: "México", group: "A" },
    { code: "RSA", name: "África do Sul", group: "A" },
    { code: "KOR", name: "Coreia do Sul", group: "A" },
    { code: "CZE", name: "Tchéquia", group: "A" },
    { code: "CAN", name: "Canadá", group: "B" },
    { code: "BIH", name: "Bósnia e Herzegovina", group: "B" },
    { code: "QAT", name: "Catar", group: "B" },
    { code: "SUI", name: "Suíça", group: "B" },
    { code: "BRA", name: "Brasil", group: "C" },
    { code: "MAR", name: "Marrocos", group: "C" },
    { code: "HTI", name: "Haiti", group: "C" },
    { code: "SCO", name: "Escócia", group: "C" },
    { code: "USA", name: "Estados Unidos", group: "D" },
    { code: "PAR", name: "Paraguai", group: "D" },
    { code: "AUS", name: "Austrália", group: "D" },
    { code: "TUR", name: "Turquia", group: "D" },
    { code: "GER", name: "Alemanha", group: "E" },
    { code: "CUW", name: "Curaçao", group: "E" },
    { code: "CIV", name: "Costa do Marfim", group: "E" },
    { code: "ECU", name: "Equador", group: "E" },
    { code: "NED", name: "Países Baixos", group: "F" },
    { code: "JPN", name: "Japão", group: "F" },
    { code: "SWE", name: "Suécia", group: "F" },
    { code: "TUN", name: "Tunísia", group: "F" },
    { code: "BEL", name: "Bélgica", group: "G" },
    { code: "EGY", name: "Egito", group: "G" },
    { code: "IRI", name: "Irã", group: "G" },
    { code: "NZL", name: "Nova Zelândia", group: "G" },
    { code: "ESP", name: "Espanha", group: "H" },
    { code: "CPV", name: "Cabo Verde", group: "H" },
    { code: "KSA", name: "Arábia Saudita", group: "H" },
    { code: "URU", name: "Uruguai", group: "H" },
    { code: "FRA", name: "França", group: "I" },
    { code: "SEN", name: "Senegal", group: "I" },
    { code: "IRQ", name: "Iraque", group: "I" },
    { code: "NOR", name: "Noruega", group: "I" },
    { code: "ARG", name: "Argentina", group: "J" },
    { code: "DZA", name: "Argélia", group: "J" },
    { code: "AUT", name: "Áustria", group: "J" },
    { code: "JOR", name: "Jordânia", group: "J" },
    { code: "POR", name: "Portugal", group: "K" },
    { code: "COD", name: "RD Congo", group: "K" },
    { code: "UZB", name: "Uzbequistão", group: "K" },
    { code: "COL", name: "Colômbia", group: "K" },
    { code: "ENG", name: "Inglaterra", group: "L" },
    { code: "CRO", name: "Croácia", group: "L" },
    { code: "GHA", name: "Gana", group: "L" },
    { code: "PAN", name: "Panamá", group: "L" }
  ],
  groupMatches: [
    { id: "GA1", group: "A", homeTeam: "MEX", awayTeam: "RSA", homeScore: 2, awayScore: 0 },
    { id: "GA2", group: "A", homeTeam: "KOR", awayTeam: "CZE", homeScore: 2, awayScore: 1 },
    { id: "GA3", group: "A", homeTeam: "CZE", awayTeam: "RSA", homeScore: 1, awayScore: 1 },
    { id: "GA4", group: "A", homeTeam: "MEX", awayTeam: "KOR", homeScore: 1, awayScore: 0 },
    { id: "GA5", group: "A", homeTeam: "CZE", awayTeam: "MEX", homeScore: null, awayScore: null },
    { id: "GA6", group: "A", homeTeam: "RSA", awayTeam: "KOR", homeScore: null, awayScore: null },
    { id: "GB1", group: "B", homeTeam: "CAN", awayTeam: "BIH", homeScore: 1, awayScore: 1 },
    { id: "GB2", group: "B", homeTeam: "QAT", awayTeam: "SUI", homeScore: 1, awayScore: 1 },
    { id: "GB3", group: "B", homeTeam: "SUI", awayTeam: "BIH", homeScore: 4, awayScore: 1 },
    { id: "GB4", group: "B", homeTeam: "CAN", awayTeam: "QAT", homeScore: 6, awayScore: 0 },
    { id: "GB5", group: "B", homeTeam: "SUI", awayTeam: "CAN", homeScore: null, awayScore: null },
    { id: "GB6", group: "B", homeTeam: "BIH", awayTeam: "QAT", homeScore: null, awayScore: null },
    { id: "GC1", group: "C", homeTeam: "BRA", awayTeam: "MAR", homeScore: 1, awayScore: 1 },
    { id: "GC2", group: "C", homeTeam: "HTI", awayTeam: "SCO", homeScore: 0, awayScore: 1 },
    { id: "GC3", group: "C", homeTeam: "SCO", awayTeam: "MAR", homeScore: 0, awayScore: 1 },
    { id: "GC4", group: "C", homeTeam: "BRA", awayTeam: "HTI", homeScore: 3, awayScore: 0 },
    { id: "GC5", group: "C", homeTeam: "SCO", awayTeam: "BRA", homeScore: null, awayScore: null },
    { id: "GC6", group: "C", homeTeam: "MAR", awayTeam: "HTI", homeScore: null, awayScore: null },
    { id: "GD1", group: "D", homeTeam: "USA", awayTeam: "PAR", homeScore: 4, awayScore: 1 },
    { id: "GD2", group: "D", homeTeam: "AUS", awayTeam: "TUR", homeScore: 2, awayScore: 0 },
    { id: "GD3", group: "D", homeTeam: "USA", awayTeam: "AUS", homeScore: 2, awayScore: 0 },
    { id: "GD4", group: "D", homeTeam: "TUR", awayTeam: "PAR", homeScore: 0, awayScore: 1 },
    { id: "GD5", group: "D", homeTeam: "TUR", awayTeam: "USA", homeScore: null, awayScore: null },
    { id: "GD6", group: "D", homeTeam: "PAR", awayTeam: "AUS", homeScore: null, awayScore: null },
    { id: "GE1", group: "E", homeTeam: "GER", awayTeam: "CUW", homeScore: 7, awayScore: 1 },
    { id: "GE2", group: "E", homeTeam: "CIV", awayTeam: "ECU", homeScore: 1, awayScore: 0 },
    { id: "GE3", group: "E", homeTeam: "GER", awayTeam: "CIV", homeScore: 2, awayScore: 1 },
    { id: "GE4", group: "E", homeTeam: "ECU", awayTeam: "CUW", homeScore: 0, awayScore: 0 },
    { id: "GE5", group: "E", homeTeam: "ECU", awayTeam: "GER", homeScore: null, awayScore: null },
    { id: "GE6", group: "E", homeTeam: "CUW", awayTeam: "CIV", homeScore: null, awayScore: null },
    { id: "GF1", group: "F", homeTeam: "NED", awayTeam: "JPN", homeScore: 2, awayScore: 2 },
    { id: "GF2", group: "F", homeTeam: "SWE", awayTeam: "TUN", homeScore: 5, awayScore: 1 },
    { id: "GF3", group: "F", homeTeam: "NED", awayTeam: "SWE", homeScore: 5, awayScore: 1 },
    { id: "GF4", group: "F", homeTeam: "TUN", awayTeam: "JPN", homeScore: 0, awayScore: 4 },
    { id: "GF5", group: "F", homeTeam: "TUN", awayTeam: "NED", homeScore: null, awayScore: null },
    { id: "GF6", group: "F", homeTeam: "JPN", awayTeam: "SWE", homeScore: null, awayScore: null },
    { id: "GG1", group: "G", homeTeam: "BEL", awayTeam: "EGY", homeScore: 1, awayScore: 1 },
    { id: "GG2", group: "G", homeTeam: "IRI", awayTeam: "NZL", homeScore: 2, awayScore: 2 },
    { id: "GG3", group: "G", homeTeam: "BEL", awayTeam: "IRI", homeScore: 0, awayScore: 0 },
    { id: "GG4", group: "G", homeTeam: "NZL", awayTeam: "EGY", homeScore: 1, awayScore: 3 },
    { id: "GG5", group: "G", homeTeam: "NZL", awayTeam: "BEL", homeScore: null, awayScore: null },
    { id: "GG6", group: "G", homeTeam: "EGY", awayTeam: "IRI", homeScore: null, awayScore: null },
    { id: "GH1", group: "H", homeTeam: "ESP", awayTeam: "CPV", homeScore: 0, awayScore: 0 },
    { id: "GH2", group: "H", homeTeam: "KSA", awayTeam: "URU", homeScore: 1, awayScore: 1 },
    { id: "GH3", group: "H", homeTeam: "ESP", awayTeam: "KSA", homeScore: 4, awayScore: 0 },
    { id: "GH4", group: "H", homeTeam: "URU", awayTeam: "CPV", homeScore: 2, awayScore: 2 },
    { id: "GH5", group: "H", homeTeam: "URU", awayTeam: "ESP", homeScore: null, awayScore: null },
    { id: "GH6", group: "H", homeTeam: "CPV", awayTeam: "KSA", homeScore: null, awayScore: null },
    { id: "GI1", group: "I", homeTeam: "FRA", awayTeam: "SEN", homeScore: 3, awayScore: 1 },
    { id: "GI2", group: "I", homeTeam: "IRQ", awayTeam: "NOR", homeScore: 1, awayScore: 4 },
    { id: "GI3", group: "I", homeTeam: "FRA", awayTeam: "IRQ", homeScore: 3, awayScore: 0 },
    { id: "GI4", group: "I", homeTeam: "NOR", awayTeam: "SEN", homeScore: 3, awayScore: 2 },
    { id: "GI5", group: "I", homeTeam: "NOR", awayTeam: "FRA", homeScore: null, awayScore: null },
    { id: "GI6", group: "I", homeTeam: "SEN", awayTeam: "IRQ", homeScore: null, awayScore: null },
    { id: "GJ1", group: "J", homeTeam: "ARG", awayTeam: "DZA", homeScore: 3, awayScore: 0 },
    { id: "GJ2", group: "J", homeTeam: "AUT", awayTeam: "JOR", homeScore: 3, awayScore: 1 },
    { id: "GJ3", group: "J", homeTeam: "ARG", awayTeam: "AUT", homeScore: 2, awayScore: 0 },
    { id: "GJ4", group: "J", homeTeam: "JOR", awayTeam: "DZA", homeScore: 1, awayScore: 2 },
    { id: "GJ5", group: "J", homeTeam: "JOR", awayTeam: "ARG", homeScore: null, awayScore: null },
    { id: "GJ6", group: "J", homeTeam: "DZA", awayTeam: "AUT", homeScore: null, awayScore: null },
    { id: "GK1", group: "K", homeTeam: "POR", awayTeam: "COD", homeScore: 1, awayScore: 1 },
    { id: "GK2", group: "K", homeTeam: "UZB", awayTeam: "COL", homeScore: 1, awayScore: 3 },
    { id: "GK3", group: "K", homeTeam: "POR", awayTeam: "UZB", homeScore: 5, awayScore: 0 },
    { id: "GK4", group: "K", homeTeam: "COL", awayTeam: "COD", homeScore: 1, awayScore: 0 },
    { id: "GK5", group: "K", homeTeam: "COL", awayTeam: "POR", homeScore: null, awayScore: null },
    { id: "GK6", group: "K", homeTeam: "COD", awayTeam: "UZB", homeScore: null, awayScore: null },
    { id: "GL1", group: "L", homeTeam: "ENG", awayTeam: "CRO", homeScore: 4, awayScore: 2 },
    { id: "GL2", group: "L", homeTeam: "GHA", awayTeam: "PAN", homeScore: 1, awayScore: 0 },
    { id: "GL3", group: "L", homeTeam: "ENG", awayTeam: "GHA", homeScore: 0, awayScore: 0 },
    { id: "GL4", group: "L", homeTeam: "PAN", awayTeam: "CRO", homeScore: 0, awayScore: 1 },
    { id: "GL5", group: "L", homeTeam: "PAN", awayTeam: "ENG", homeScore: null, awayScore: null },
    { id: "GL6", group: "L", homeTeam: "CRO", awayTeam: "GHA", homeScore: null, awayScore: null }
  ],
  knockoutMatches: [
    { id: "K1", stage: "32 avos", side: "left", homeSlot: "1E", awaySlot: "3 ABCDF", kickoff: "29/06 • 17h30", nextMatchId: "O1" },
    { id: "K2", stage: "32 avos", side: "left", homeSlot: "1I", awaySlot: "3 CDFGH", kickoff: "30/06 • 18h00", nextMatchId: "O1" },
    { id: "K3", stage: "32 avos", side: "left", homeSlot: "2A", awaySlot: "2B", kickoff: "28/06 • 16h00", nextMatchId: "O2" },
    { id: "K4", stage: "32 avos", side: "left", homeSlot: "1F", awaySlot: "2C", kickoff: "29/06 • 22h00", nextMatchId: "O2" },
    { id: "K5", stage: "32 avos", side: "left", homeSlot: "2K", awaySlot: "2L", kickoff: "02/07 • 20h00", nextMatchId: "O3" },
    { id: "K6", stage: "32 avos", side: "left", homeSlot: "1H", awaySlot: "2J", kickoff: "02/07 • 16h00", nextMatchId: "O3" },
    { id: "K7", stage: "32 avos", side: "left", homeSlot: "1D", awaySlot: "3 BEFIJ", kickoff: "01/07 • 21h00", nextMatchId: "O4" },
    { id: "K8", stage: "32 avos", side: "left", homeSlot: "1G", awaySlot: "3 AEHIJ", kickoff: "01/07 • 17h00", nextMatchId: "O4" },
    { id: "K9", stage: "32 avos", side: "right", homeSlot: "1C", awaySlot: "2F", kickoff: "29/06 • 14h00", nextMatchId: "O5" },
    { id: "K10", stage: "32 avos", side: "right", homeSlot: "2E", awaySlot: "2I", kickoff: "30/06 • 14h00", nextMatchId: "O5" },
    { id: "K11", stage: "32 avos", side: "right", homeSlot: "1A", awaySlot: "3 CEFHI", kickoff: "30/06 • 22h00", nextMatchId: "O6" },
    { id: "K12", stage: "32 avos", side: "right", homeSlot: "1L", awaySlot: "3 EHIJK", kickoff: "01/07 • 13h00", nextMatchId: "O6" },
    { id: "K13", stage: "32 avos", side: "right", homeSlot: "1J", awaySlot: "2H", kickoff: "03/07 • 19h00", nextMatchId: "O7" },
    { id: "K14", stage: "32 avos", side: "right", homeSlot: "2D", awaySlot: "2G", kickoff: "03/07 • 15h00", nextMatchId: "O7" },
    { id: "K15", stage: "32 avos", side: "right", homeSlot: "1B", awaySlot: "3 EFGIJ", kickoff: "03/07 • 00h00", nextMatchId: "O8" },
    { id: "K16", stage: "32 avos", side: "right", homeSlot: "1K", awaySlot: "3 DEIJL", kickoff: "03/07 • 22h30", nextMatchId: "O8" },
    { id: "O1", stage: "oitavas", side: "left", homeSlot: "K1", awaySlot: "K2", kickoff: "04/07 • 18h00", nextMatchId: "Q1" },
    { id: "O2", stage: "oitavas", side: "left", homeSlot: "K3", awaySlot: "K4", kickoff: "04/07 • 14h00", nextMatchId: "Q1" },
    { id: "O3", stage: "oitavas", side: "left", homeSlot: "K5", awaySlot: "K6", kickoff: "06/07 • 16h00", nextMatchId: "Q2" },
    { id: "O4", stage: "oitavas", side: "left", homeSlot: "K7", awaySlot: "K8", kickoff: "06/07 • 21h00", nextMatchId: "Q2" },
    { id: "O5", stage: "oitavas", side: "right", homeSlot: "K9", awaySlot: "K10", kickoff: "05/07 • 17h00", nextMatchId: "Q3" },
    { id: "O6", stage: "oitavas", side: "right", homeSlot: "K11", awaySlot: "K12", kickoff: "05/07 • 21h00", nextMatchId: "Q3" },
    { id: "O7", stage: "oitavas", side: "right", homeSlot: "K13", awaySlot: "K14", kickoff: "07/07 • 13h00", nextMatchId: "Q4" },
    { id: "O8", stage: "oitavas", side: "right", homeSlot: "K15", awaySlot: "K16", kickoff: "07/07 • 17h00", nextMatchId: "Q4" },
    { id: "Q1", stage: "quartas", side: "left", homeSlot: "O1", awaySlot: "O2", kickoff: "09/07 • 17h00", nextMatchId: "S1" },
    { id: "Q2", stage: "quartas", side: "left", homeSlot: "O3", awaySlot: "O4", kickoff: "10/07 • 16h00", nextMatchId: "S1" },
    { id: "Q3", stage: "quartas", side: "right", homeSlot: "O5", awaySlot: "O6", kickoff: "11/07 • 18h00", nextMatchId: "S2" },
    { id: "Q4", stage: "quartas", side: "right", homeSlot: "O7", awaySlot: "O8", kickoff: "11/07 • 22h00", nextMatchId: "S2" },
    { id: "S1", stage: "semifinal", side: "left", homeSlot: "Q1", awaySlot: "Q2", kickoff: "14/07 • 16h00", nextMatchId: "F" },
    { id: "S2", stage: "semifinal", side: "right", homeSlot: "Q3", awaySlot: "Q4", kickoff: "15/07 • 16h00", nextMatchId: "F" },
    { id: "F", stage: "final", side: "center", homeSlot: "S1", awaySlot: "S2", kickoff: "19/07 • 16h00" },
    { id: "T", stage: "3º lugar", side: "center", homeSlot: "S1", awaySlot: "S2", kickoff: "18/07 • 18h00" }
  ]
};
